version: '3'

volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: owningglory/kittygram_backend
    env_file:
      - .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
  frontend:
    image: owningglory/kittygram_frontend
    env_file:
      - .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - db
  gateway:
    image: owningglory/kittygram_gateway
    env_file:
      - .env
    volumes:
      - static:/static/
      - media:/media
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
